#!/bin/sh
usage()
{
    cat <<EOF
Usage: rgesolver-config [OPTION]

Known values for OPTION are:

  --libs                print library linking information
  --cflags              print pre-processor and compiler flags

EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

pkg-config $@ /home/oem/RGESolver/Solver/RGESolver.pc
